apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: amqps://occnzyot:5ASBKGnpHtDZpaVI1JEOa0Sc_70W2BBp@rabbitmq-cluster/occnzyot
    - name: port
      value: 5672
    - name: username
      value: occnzyot
    - name: password
      value: 5ASBKGnpHtDZpaVI1JEOa0Sc_70W2BBp
    - name: durable
      value: "true"
    - name: autoDelete
      value: "true"
