apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: amqps://user:pass@puffin.rmq2.example.com/ioraopuk
    - name: port
      value: 5672
    - name: username
      value: user
    - name: password
      value: pass
    - name: durable
      value: "true"
    - name: autoDelete
      value: "true"
