name: GitLeaks Scan

on:
  push:
    branches:
      - '**'  
  pull_request:  
  workflow_dispatch:

jobs:
  gitleaks:
    name: GitLeaks Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write  
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-path: .gitleaks.toml  
          enable-upload-artifact: true
          report-format: sarif
          report-path: gitleaks-report.sarif

    